# Generated by Django 4.1.7 on 2023-04-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0009_reviewrating_fn_reviewrating_img_reviewrating_ln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='photo',
            field=models.ImageField(default='user-profile.png', null=True, upload_to='Profiles/'),
        ),
    ]
